"""initial schema with user and tax tables

Revision ID: 6eba39401e80
Revises: 
Create Date: 2026-04-29 16:51:41.213393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eba39401e80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paystubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('payee', sa.String(), nullable=False),
    sa.Column('expected_gross_pay', sa.Float(), nullable=False),
    sa.Column('actual_gross_pay', sa.Float(), nullable=False),
    sa.Column('pre_tax_retirement_contribution', sa.Float(), nullable=False),
    sa.Column('post_tax_retirement_contribution', sa.Float(), nullable=False),
    sa.Column('medical_dental_pre_tax_contribution', sa.Float(), nullable=False),
    sa.Column('federal_witholding', sa.Float(), nullable=False),
    sa.Column('state_witholding', sa.Float(), nullable=False),
    sa.Column('social_security_tax', sa.Float(), nullable=False),
    sa.Column('medicare_tax', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('paystubs')
    # ### end Alembic commands ###
